config/routes.rb
GameContestServer::Application.routes.draw do
  root 'users#index'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
	resources :referees
	resources :contests do
		resources :players, shallow: true
    resources :matches, shallow: true, only:[ :index, :show ]
	end
  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
	
	has_many :referees
  has_many :contests
  has_many :players
  
  validates :username, presence: true, uniqueness: true, length: {maximum: 20}
  validates :email, presence: true, format: {with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i}
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :ensure_user_logged_in,     only: [:edit, :update]
  before_action :ensure_not_logged_in,      only: [:create, :new]
	before_action :ensure_correct_user,       only: [:edit, :update]
	before_action :ensure_admin_user,         only: [:destroy]
  
  respond_to :html, :json, :xml
  
  def index
    @users = User.all
    respond_with(@user)
  end
  
  def new
    @user = User.new
    respond_with(@user)
  end
  
  def create
    @user = User.new(permitted_params)
    if @user.save
      log_in(@user)
      flash[:success] = "Welcome to the site: #{@user.username}"
    end
    respond_with(@user)
  end
    
  def show
    @user = User.find(params[:id])
    respond_with(@user)
  end
    
  def edit
  end
    
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(permitted_params)
      flash[:success] = "You successfully updated your profile."
    end
    respond_with(@user)
  end
  
  def destroy
    @user.destroy
    flash[:success] = "User destroyed."
    respond_with(@user)
  end
    
  private
  def permitted_params
    permitted_params = params.require(:user).permit(:username, :email, :password, :password_confirmation) 
  end
  
  def ensure_user_logged_in
    if !logged_in?
      flash[:warning] = "You are not logged in!"
      redirect_to login_path
    end
  end

  def ensure_not_logged_in
    if logged_in?
      flash[:warning] = "You are logged in!"
      redirect_to root_path
    end
  end
	
	def ensure_correct_user
    @user = User.find(params[:id])
    if !current_user?(@user)
      flash[:danger] = "This is not you."
  		redirect_to root_path
    end
	end
	
	def ensure_admin_user
    @user = User.find(params[:id])
    if !current_user.admin? || current_user?(@user)
      redirect_to root_path, flash: { :danger => "Must be admin!" }
    end
	end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/.html.erb
works

app/views/users/_user.html.erb
<li> 
  <%= link_to user.username, user_path(user) %>
  <% if current_user && current_user.admin? && !current_user?(user) %>
    | <%= link_to 'edit', edit_user_path(user) %>
  	| <%= link_to 'delete', user_path(user), method: :delete, data: {confirm: "Are you sure you want to delete #{user.username}?"} %>
  <% end %>
</li>

app/views/users/_user_form.html.erb
<%= form_for @user do |f| %>
<% if @user.errors.any? %>
<div class="alert alert-danger">
<p>There have <%= pluralize(@user.errors.count, 'error') %> </p>
</div>
<ul>
  <% @user.errors.full_messages.each do |message| %>
  <li class="text-danger"><%= message %></li>
  <% end %>
</ul>
<% end %>

<%= f.label :username, 'Username' %>
<%= f.text_field :username, class: 'form-control' %>

<%= f.label :email, 'Email' %>
<%= f.text_field :email, class: 'form-control' %>

<%= f.label :chat_url, 'Chat_Url' %>
<%= f.text_field :chat_url, class: 'form-control' %>

<%= f.label :password, 'Password' %>
<%= f.password_field :password, class: 'form-control' %>

<%= f.label :password_confirmation, 'Confirmation' %>
<%= f.password_field :password_confirmation, class: 'form-control' %>
<br />
<%= f.submit button_label, class: 'btn btn-primary'%>
<br /><br />
<% end %>

app/views/users/_user_players.html.erb
<li>
  <%= link_to player.name, player_path(player) %> |
  <%= link_to "edit", edit_player_path(player) %>
  <% if current_user?(player.user) %>
    | <%= link_to "delete", player_path(player), method: :delete, data: {confirm: "Are you sure you want to delete #{player.name}?"} %>
  <% end %>
</li>

app/views/users/_user_referees.html.erb
<li>
  <%= link_to referee.name, referee_path(referee) %> |
  <%= link_to "edit", edit_referee_path(referee) %>
  <% if logged_in? %>
    | <%= link_to "delete", referee_path(referee), method: :delete, data: {confirm: "Are you sure you want to delete #{referee.name}?"} %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update Profile</h1>

<%= form_for @user do |form| %>
	<%= render 'user_form', f: form, button_label: 'Update account' %>
<% end %>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>List of users</h1>

<h4><%= @users.length %> users</h4>

<ul>
	<%= render @users %>
</ul>

app/views/users/new.html.erb
<% provide(:title, 'Sign up!') %>
<h1>Sign up!</h1>

<%= form_for @user do |form| %>
<%= render 'user_form', f: form, button_label: 'Create new account' %>
<% end %>

app/views/users/show.html.erb
<% provide(:title, @user.username) %>
<h2>User information</h2>
<p>Name: <%= @user.username %> | <%= link_to "edit", edit_user_path(@user) %></p>
<ul>
  <li>Email: <%= @user.email %></li>
  <li>Chat Url: <%= @user.chat_url %></li>
</ul>

<% if @user.contest_creator? %>
<h2>Referees</h2>
<h4><%= @user.referees.length%> referees</h4>
<ul>
  <%= render partial: "user_referees", collection: @user.referees, as: :referee %>
</ul>
<p><%= link_to "New Referee", new_referee_path %></p>
<% end %>

<h2>Players</h2>
<h4><%= @user.players.length %> players </h4>
<ul>
  <%= render partial: "user_players", collection: @user.players, as: :player %>
</ul>