config/routes.rb
GameContestServer::Application.routes.draw do
  root 'users#index'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
	resources :referees
	resources :contests do
		resources :players, shallow: true
    resources :matches, shallow: true, only:[ :index, :show ]
	end
  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  

end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :manager, polymorphic: true
  belongs_to :referee
  belongs_to :contest
  
  has_many :players, through: :player_matches
  has_many :player_matches
  
  validates :manager, presence: true
  validates :status, presence: true
  validates_date :completion, :on_or_before => lambda { Time.now.change(:usec =>0) }, :if => :check_finished_matches
  validates_datetime :earliest_start, :if => :check_started_matches
	validate :check_num_players
  
  def check_finished_matches
    if self.status != "Completed"
      return nil
    else
      return true
    end
  end
  
  def check_started_matches
    if self.status == "Completed"
      return nil
    elsif self.status == "Started"
      return nil
    else
      return true
    end
  end
	
	def check_num_players
		if self.players && self.manager
			if self.players.count != self.manager.referee.players_per_game
				errors.add(:manager, "Too many/few players!")
			end
		end
	end
  
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  
  def index
    @contest = Contest.find(params[:contest_id])
    @matches = Match.all
  end
  
  def show
    @match = Match.find(params[:id])
  end
  
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/index.html.erb
<% provide(:title, 'All Matches') %>
<h2>Matches</h2>

<ul>
  <% @matches.each do |f| %>
    <% if f.manager_id == @contest.id %>
      <li><%= link_to f.id, match_path(f) %></li>
    <% end %>
  <% end %>
</ul>

app/views/matches/show.html.erb
<h2>Match</h2>
<ul>
  <li>Match Status: <%= @match.status %></li>
  <li>Start Time: <%= distance_of_time_in_words_to_now(@match.earliest_start) %></li>
  <li>Match Manager Name: <%= @match.manager.name %></li>
  <li>Match Manager Referee Name: <%= @match.manager.referee.name %></li>
  <li>Match Players Per Game: <%= @match.manager.referee.players_per_game %></li>
</ul>

<p>Completion: <%= distance_of_time_in_words_to_now(@match.completion) %></p>

<ol>
	<% @match.player_matches.order(score: :desc).each do |player_matches| %>
		<li><%= link_to player_matches.player.name, player_path(player_matches.player) %> - <%= player_matches.score %></li>
	<% end %>
</ol>